// var data = [
//     {
//         "id": 23745385,
//         "name": "A7-JSIteration",
//         "full_name": "plove13x/A7-JSIteration",
//         "owner": {
//             "login": "plove13x",
//             "id": 7731175,
//             "avatar_url": "https://avatars.githubusercontent.com/u/7731175?v=2",
//             "gravatar_id": "f6bfe421126c91d30029e954e8f1ee26",
//             "url": "https://api.github.com/users/plove13x",
//             "html_url": "https://github.com/plove13x",
//             "followers_url": "https://api.github.com/users/plove13x/followers",
//             "following_url": "https://api.github.com/users/plove13x/following{/other_user}",
//             "gists_url": "https://api.github.com/users/plove13x/gists{/gist_id}",
//             "starred_url": "https://api.github.com/users/plove13x/starred{/owner}{/repo}",
//             "subscriptions_url": "https://api.github.com/users/plove13x/subscriptions",
//             "organizations_url": "https://api.github.com/users/plove13x/orgs",
//             "repos_url": "https://api.github.com/users/plove13x/repos",
//             "events_url": "https://api.github.com/users/plove13x/events{/privacy}",
//             "received_events_url": "https://api.github.com/users/plove13x/received_events",
//             "type": "User",
//             "site_admin": false
//         },
//         "private": false,
//         "html_url": "https://github.com/plove13x/A7-JSIteration",
//         "description": null,
//         "fork": false,
//         "url": "https://api.github.com/repos/plove13x/A7-JSIteration",
//         "forks_url": "https://api.github.com/repos/plove13x/A7-JSIteration/forks",
//         "keys_url": "https://api.github.com/repos/plove13x/A7-JSIteration/keys{/key_id}",
//         "collaborators_url": "https://api.github.com/repos/plove13x/A7-JSIteration/collaborators{/collaborator}",
//         "teams_url": "https://api.github.com/repos/plove13x/A7-JSIteration/teams",
//         "hooks_url": "https://api.github.com/repos/plove13x/A7-JSIteration/hooks",
//         "issue_events_url": "https://api.github.com/repos/plove13x/A7-JSIteration/issues/events{/number}",
//         "events_url": "https://api.github.com/repos/plove13x/A7-JSIteration/events",
//         "assignees_url": "https://api.github.com/repos/plove13x/A7-JSIteration/assignees{/user}",
//         "branches_url": "https://api.github.com/repos/plove13x/A7-JSIteration/branches{/branch}",
//         "tags_url": "https://api.github.com/repos/plove13x/A7-JSIteration/tags",
//         "blobs_url": "https://api.github.com/repos/plove13x/A7-JSIteration/git/blobs{/sha}",
//         "git_tags_url": "https://api.github.com/repos/plove13x/A7-JSIteration/git/tags{/sha}",
//         "git_refs_url": "https://api.github.com/repos/plove13x/A7-JSIteration/git/refs{/sha}",
//         "trees_url": "https://api.github.com/repos/plove13x/A7-JSIteration/git/trees{/sha}",
//         "statuses_url": "https://api.github.com/repos/plove13x/A7-JSIteration/statuses/{sha}",
//         "languages_url": "https://api.github.com/repos/plove13x/A7-JSIteration/languages",
//         "stargazers_url": "https://api.github.com/repos/plove13x/A7-JSIteration/stargazers",
//         "contributors_url": "https://api.github.com/repos/plove13x/A7-JSIteration/contributors",
//         "subscribers_url": "https://api.github.com/repos/plove13x/A7-JSIteration/subscribers",
//         "subscription_url": "https://api.github.com/repos/plove13x/A7-JSIteration/subscription",
//         "commits_url": "https://api.github.com/repos/plove13x/A7-JSIteration/commits{/sha}",
//         "git_commits_url": "https://api.github.com/repos/plove13x/A7-JSIteration/git/commits{/sha}",
//         "comments_url": "https://api.github.com/repos/plove13x/A7-JSIteration/comments{/number}",
//         "issue_comment_url": "https://api.github.com/repos/plove13x/A7-JSIteration/issues/comments/{number}",
//         "contents_url": "https://api.github.com/repos/plove13x/A7-JSIteration/contents/{+path}",
//         "compare_url": "https://api.github.com/repos/plove13x/A7-JSIteration/compare/{base}...{head}",
//         "merges_url": "https://api.github.com/repos/plove13x/A7-JSIteration/merges",
//         "archive_url": "https://api.github.com/repos/plove13x/A7-JSIteration/{archive_format}{/ref}",
//         "downloads_url": "https://api.github.com/repos/plove13x/A7-JSIteration/downloads",
//         "issues_url": "https://api.github.com/repos/plove13x/A7-JSIteration/issues{/number}",
//         "pulls_url": "https://api.github.com/repos/plove13x/A7-JSIteration/pulls{/number}",
//         "milestones_url": "https://api.github.com/repos/plove13x/A7-JSIteration/milestones{/number}",
//         "notifications_url": "https://api.github.com/repos/plove13x/A7-JSIteration/notifications{?since,all,participating}",
//         "labels_url": "https://api.github.com/repos/plove13x/A7-JSIteration/labels{/name}",
//         "releases_url": "https://api.github.com/repos/plove13x/A7-JSIteration/releases{/id}",
//         "created_at": "2014-09-06T21:07:05Z",
//         "updated_at": "2014-09-06T21:07:31Z",
//         "pushed_at": "2014-09-06T21:07:31Z",
//         "git_url": "git://github.com/plove13x/A7-JSIteration.git",
//         "ssh_url": "git@github.com:plove13x/A7-JSIteration.git",
//         "clone_url": "https://github.com/plove13x/A7-JSIteration.git",
//         "svn_url": "https://github.com/plove13x/A7-JSIteration",
//         "homepage": null,
//         "size": 0,
//         "stargazers_count": 0,
//         "watchers_count": 0,
//         "language": "JavaScript",
//         "has_issues": true,
//         "has_downloads": true,
//         "has_wiki": true,
//         "forks_count": 0,
//         "mirror_url": null,
//         "open_issues_count": 0,
//         "forks": 0,
//         "open_issues": 0,
//         "watchers": 0,
//         "default_branch": "master"
//     },
//     {
//         "id": 23820946,
//         "name": "A8-Coercions-jQueryAccordion",
//         "full_name": "plove13x/A8-Coercions-jQueryAccordion",
//         "owner": {
//             "login": "plove13x",
//             "id": 7731175,
//             "avatar_url": "https://avatars.githubusercontent.com/u/7731175?v=2",
//             "gravatar_id": "f6bfe421126c91d30029e954e8f1ee26",
//             "url": "https://api.github.com/users/plove13x",
//             "html_url": "https://github.com/plove13x",
//             "followers_url": "https://api.github.com/users/plove13x/followers",
//             "following_url": "https://api.github.com/users/plove13x/following{/other_user}",
//             "gists_url": "https://api.github.com/users/plove13x/gists{/gist_id}",
//             "starred_url": "https://api.github.com/users/plove13x/starred{/owner}{/repo}",
//             "subscriptions_url": "https://api.github.com/users/plove13x/subscriptions",
//             "organizations_url": "https://api.github.com/users/plove13x/orgs",
//             "repos_url": "https://api.github.com/users/plove13x/repos",
//             "events_url": "https://api.github.com/users/plove13x/events{/privacy}",
//             "received_events_url": "https://api.github.com/users/plove13x/received_events",
//             "type": "User",
//             "site_admin": false
//         },
//         "private": false,
//         "html_url": "https://github.com/plove13x/A8-Coercions-jQueryAccordion",
//         "description": null,
//         "fork": false,
//         "url": "https://api.github.com/repos/plove13x/A8-Coercions-jQueryAccordion",
//         "forks_url": "https://api.github.com/repos/plove13x/A8-Coercions-jQueryAccordion/forks",
//         "keys_url": "https://api.github.com/repos/plove13x/A8-Coercions-jQueryAccordion/keys{/key_id}",
//         "collaborators_url": "https://api.github.com/repos/plove13x/A8-Coercions-jQueryAccordion/collaborators{/collaborator}",
//         "teams_url": "https://api.github.com/repos/plove13x/A8-Coercions-jQueryAccordion/teams",
//         "hooks_url": "https://api.github.com/repos/plove13x/A8-Coercions-jQueryAccordion/hooks",
//         "issue_events_url": "https://api.github.com/repos/plove13x/A8-Coercions-jQueryAccordion/issues/events{/number}",
//         "events_url": "https://api.github.com/repos/plove13x/A8-Coercions-jQueryAccordion/events",
//         "assignees_url": "https://api.github.com/repos/plove13x/A8-Coercions-jQueryAccordion/assignees{/user}",
//         "branches_url": "https://api.github.com/repos/plove13x/A8-Coercions-jQueryAccordion/branches{/branch}",
//         "tags_url": "https://api.github.com/repos/plove13x/A8-Coercions-jQueryAccordion/tags",
//         "blobs_url": "https://api.github.com/repos/plove13x/A8-Coercions-jQueryAccordion/git/blobs{/sha}",
//         "git_tags_url": "https://api.github.com/repos/plove13x/A8-Coercions-jQueryAccordion/git/tags{/sha}",
//         "git_refs_url": "https://api.github.com/repos/plove13x/A8-Coercions-jQueryAccordion/git/refs{/sha}",
//         "trees_url": "https://api.github.com/repos/plove13x/A8-Coercions-jQueryAccordion/git/trees{/sha}",
//         "statuses_url": "https://api.github.com/repos/plove13x/A8-Coercions-jQueryAccordion/statuses/{sha}",
//         "languages_url": "https://api.github.com/repos/plove13x/A8-Coercions-jQueryAccordion/languages",
//         "stargazers_url": "https://api.github.com/repos/plove13x/A8-Coercions-jQueryAccordion/stargazers",
//         "contributors_url": "https://api.github.com/repos/plove13x/A8-Coercions-jQueryAccordion/contributors",
//         "subscribers_url": "https://api.github.com/repos/plove13x/A8-Coercions-jQueryAccordion/subscribers",
//         "subscription_url": "https://api.github.com/repos/plove13x/A8-Coercions-jQueryAccordion/subscription",
//         "commits_url": "https://api.github.com/repos/plove13x/A8-Coercions-jQueryAccordion/commits{/sha}",
//         "git_commits_url": "https://api.github.com/repos/plove13x/A8-Coercions-jQueryAccordion/git/commits{/sha}",
//         "comments_url": "https://api.github.com/repos/plove13x/A8-Coercions-jQueryAccordion/comments{/number}",
//         "issue_comment_url": "https://api.github.com/repos/plove13x/A8-Coercions-jQueryAccordion/issues/comments/{number}",
//         "contents_url": "https://api.github.com/repos/plove13x/A8-Coercions-jQueryAccordion/contents/{+path}",
//         "compare_url": "https://api.github.com/repos/plove13x/A8-Coercions-jQueryAccordion/compare/{base}...{head}",
//         "merges_url": "https://api.github.com/repos/plove13x/A8-Coercions-jQueryAccordion/merges",
//         "archive_url": "https://api.github.com/repos/plove13x/A8-Coercions-jQueryAccordion/{archive_format}{/ref}",
//         "downloads_url": "https://api.github.com/repos/plove13x/A8-Coercions-jQueryAccordion/downloads",
//         "issues_url": "https://api.github.com/repos/plove13x/A8-Coercions-jQueryAccordion/issues{/number}",
//         "pulls_url": "https://api.github.com/repos/plove13x/A8-Coercions-jQueryAccordion/pulls{/number}",
//         "milestones_url": "https://api.github.com/repos/plove13x/A8-Coercions-jQueryAccordion/milestones{/number}",
//         "notifications_url": "https://api.github.com/repos/plove13x/A8-Coercions-jQueryAccordion/notifications{?since,all,participating}",
//         "labels_url": "https://api.github.com/repos/plove13x/A8-Coercions-jQueryAccordion/labels{/name}",
//         "releases_url": "https://api.github.com/repos/plove13x/A8-Coercions-jQueryAccordion/releases{/id}",
//         "created_at": "2014-09-09T05:46:13Z",
//         "updated_at": "2014-09-09T05:46:46Z",
//         "pushed_at": "2014-09-09T05:46:47Z",
//         "git_url": "git://github.com/plove13x/A8-Coercions-jQueryAccordion.git",
//         "ssh_url": "git@github.com:plove13x/A8-Coercions-jQueryAccordion.git",
//         "clone_url": "https://github.com/plove13x/A8-Coercions-jQueryAccordion.git",
//         "svn_url": "https://github.com/plove13x/A8-Coercions-jQueryAccordion",
//         "homepage": null,
//         "size": 0,
//         "stargazers_count": 0,
//         "watchers_count": 0,
//         "language": "CSS",
//         "has_issues": true,
//         "has_downloads": true,
//         "has_wiki": true,
//         "forks_count": 0,
//         "mirror_url": null,
//         "open_issues_count": 0,
//         "forks": 0,
//         "open_issues": 0,
//         "watchers": 0,
//         "default_branch": "master"
//     },
//     {
//         "id": 23859713,
//         "name": "A9-EtsyAPI",
//         "full_name": "plove13x/A9-EtsyAPI",
//         "owner": {
//             "login": "plove13x",
//             "id": 7731175,
//             "avatar_url": "https://avatars.githubusercontent.com/u/7731175?v=2",
//             "gravatar_id": "f6bfe421126c91d30029e954e8f1ee26",
//             "url": "https://api.github.com/users/plove13x",
//             "html_url": "https://github.com/plove13x",
//             "followers_url": "https://api.github.com/users/plove13x/followers",
//             "following_url": "https://api.github.com/users/plove13x/following{/other_user}",
//             "gists_url": "https://api.github.com/users/plove13x/gists{/gist_id}",
//             "starred_url": "https://api.github.com/users/plove13x/starred{/owner}{/repo}",
//             "subscriptions_url": "https://api.github.com/users/plove13x/subscriptions",
//             "organizations_url": "https://api.github.com/users/plove13x/orgs",
//             "repos_url": "https://api.github.com/users/plove13x/repos",
//             "events_url": "https://api.github.com/users/plove13x/events{/privacy}",
//             "received_events_url": "https://api.github.com/users/plove13x/received_events",
//             "type": "User",
//             "site_admin": false
//         },
//         "private": false,
//         "html_url": "https://github.com/plove13x/A9-EtsyAPI",
//         "description": null,
//         "fork": false,
//         "url": "https://api.github.com/repos/plove13x/A9-EtsyAPI",
//         "forks_url": "https://api.github.com/repos/plove13x/A9-EtsyAPI/forks",
//         "keys_url": "https://api.github.com/repos/plove13x/A9-EtsyAPI/keys{/key_id}",
//         "collaborators_url": "https://api.github.com/repos/plove13x/A9-EtsyAPI/collaborators{/collaborator}",
//         "teams_url": "https://api.github.com/repos/plove13x/A9-EtsyAPI/teams",
//         "hooks_url": "https://api.github.com/repos/plove13x/A9-EtsyAPI/hooks",
//         "issue_events_url": "https://api.github.com/repos/plove13x/A9-EtsyAPI/issues/events{/number}",
//         "events_url": "https://api.github.com/repos/plove13x/A9-EtsyAPI/events",
//         "assignees_url": "https://api.github.com/repos/plove13x/A9-EtsyAPI/assignees{/user}",
//         "branches_url": "https://api.github.com/repos/plove13x/A9-EtsyAPI/branches{/branch}",
//         "tags_url": "https://api.github.com/repos/plove13x/A9-EtsyAPI/tags",
//         "blobs_url": "https://api.github.com/repos/plove13x/A9-EtsyAPI/git/blobs{/sha}",
//         "git_tags_url": "https://api.github.com/repos/plove13x/A9-EtsyAPI/git/tags{/sha}",
//         "git_refs_url": "https://api.github.com/repos/plove13x/A9-EtsyAPI/git/refs{/sha}",
//         "trees_url": "https://api.github.com/repos/plove13x/A9-EtsyAPI/git/trees{/sha}",
//         "statuses_url": "https://api.github.com/repos/plove13x/A9-EtsyAPI/statuses/{sha}",
//         "languages_url": "https://api.github.com/repos/plove13x/A9-EtsyAPI/languages",
//         "stargazers_url": "https://api.github.com/repos/plove13x/A9-EtsyAPI/stargazers",
//         "contributors_url": "https://api.github.com/repos/plove13x/A9-EtsyAPI/contributors",
//         "subscribers_url": "https://api.github.com/repos/plove13x/A9-EtsyAPI/subscribers",
//         "subscription_url": "https://api.github.com/repos/plove13x/A9-EtsyAPI/subscription",
//         "commits_url": "https://api.github.com/repos/plove13x/A9-EtsyAPI/commits{/sha}",
//         "git_commits_url": "https://api.github.com/repos/plove13x/A9-EtsyAPI/git/commits{/sha}",
//         "comments_url": "https://api.github.com/repos/plove13x/A9-EtsyAPI/comments{/number}",
//         "issue_comment_url": "https://api.github.com/repos/plove13x/A9-EtsyAPI/issues/comments/{number}",
//         "contents_url": "https://api.github.com/repos/plove13x/A9-EtsyAPI/contents/{+path}",
//         "compare_url": "https://api.github.com/repos/plove13x/A9-EtsyAPI/compare/{base}...{head}",
//         "merges_url": "https://api.github.com/repos/plove13x/A9-EtsyAPI/merges",
//         "archive_url": "https://api.github.com/repos/plove13x/A9-EtsyAPI/{archive_format}{/ref}",
//         "downloads_url": "https://api.github.com/repos/plove13x/A9-EtsyAPI/downloads",
//         "issues_url": "https://api.github.com/repos/plove13x/A9-EtsyAPI/issues{/number}",
//         "pulls_url": "https://api.github.com/repos/plove13x/A9-EtsyAPI/pulls{/number}",
//         "milestones_url": "https://api.github.com/repos/plove13x/A9-EtsyAPI/milestones{/number}",
//         "notifications_url": "https://api.github.com/repos/plove13x/A9-EtsyAPI/notifications{?since,all,participating}",
//         "labels_url": "https://api.github.com/repos/plove13x/A9-EtsyAPI/labels{/name}",
//         "releases_url": "https://api.github.com/repos/plove13x/A9-EtsyAPI/releases{/id}",
//         "created_at": "2014-09-10T03:42:20Z",
//         "updated_at": "2014-09-10T03:44:29Z",
//         "pushed_at": "2014-09-10T03:44:29Z",
//         "git_url": "git://github.com/plove13x/A9-EtsyAPI.git",
//         "ssh_url": "git@github.com:plove13x/A9-EtsyAPI.git",
//         "clone_url": "https://github.com/plove13x/A9-EtsyAPI.git",
//         "svn_url": "https://github.com/plove13x/A9-EtsyAPI",
//         "homepage": null,
//         "size": 0,
//         "stargazers_count": 0,
//         "watchers_count": 0,
//         "language": "JavaScript",
//         "has_issues": true,
//         "has_downloads": true,
//         "has_wiki": true,
//         "forks_count": 0,
//         "mirror_url": null,
//         "open_issues_count": 0,
//         "forks": 0,
//         "open_issues": 0,
//         "watchers": 0,
//         "default_branch": "master"
//     },
//     {
//         "id": 23126948,
//         "name": "hello-world",
//         "full_name": "plove13x/hello-world",
//         "owner": {
//             "login": "plove13x",
//             "id": 7731175,
//             "avatar_url": "https://avatars.githubusercontent.com/u/7731175?v=2",
//             "gravatar_id": "f6bfe421126c91d30029e954e8f1ee26",
//             "url": "https://api.github.com/users/plove13x",
//             "html_url": "https://github.com/plove13x",
//             "followers_url": "https://api.github.com/users/plove13x/followers",
//             "following_url": "https://api.github.com/users/plove13x/following{/other_user}",
//             "gists_url": "https://api.github.com/users/plove13x/gists{/gist_id}",
//             "starred_url": "https://api.github.com/users/plove13x/starred{/owner}{/repo}",
//             "subscriptions_url": "https://api.github.com/users/plove13x/subscriptions",
//             "organizations_url": "https://api.github.com/users/plove13x/orgs",
//             "repos_url": "https://api.github.com/users/plove13x/repos",
//             "events_url": "https://api.github.com/users/plove13x/events{/privacy}",
//             "received_events_url": "https://api.github.com/users/plove13x/received_events",
//             "type": "User",
//             "site_admin": false
//         },
//         "private": false,
//         "html_url": "https://github.com/plove13x/hello-world",
//         "description": "Jake's Orders",
//         "fork": false,
//         "url": "https://api.github.com/repos/plove13x/hello-world",
//         "forks_url": "https://api.github.com/repos/plove13x/hello-world/forks",
//         "keys_url": "https://api.github.com/repos/plove13x/hello-world/keys{/key_id}",
//         "collaborators_url": "https://api.github.com/repos/plove13x/hello-world/collaborators{/collaborator}",
//         "teams_url": "https://api.github.com/repos/plove13x/hello-world/teams",
//         "hooks_url": "https://api.github.com/repos/plove13x/hello-world/hooks",
//         "issue_events_url": "https://api.github.com/repos/plove13x/hello-world/issues/events{/number}",
//         "events_url": "https://api.github.com/repos/plove13x/hello-world/events",
//         "assignees_url": "https://api.github.com/repos/plove13x/hello-world/assignees{/user}",
//         "branches_url": "https://api.github.com/repos/plove13x/hello-world/branches{/branch}",
//         "tags_url": "https://api.github.com/repos/plove13x/hello-world/tags",
//         "blobs_url": "https://api.github.com/repos/plove13x/hello-world/git/blobs{/sha}",
//         "git_tags_url": "https://api.github.com/repos/plove13x/hello-world/git/tags{/sha}",
//         "git_refs_url": "https://api.github.com/repos/plove13x/hello-world/git/refs{/sha}",
//         "trees_url": "https://api.github.com/repos/plove13x/hello-world/git/trees{/sha}",
//         "statuses_url": "https://api.github.com/repos/plove13x/hello-world/statuses/{sha}",
//         "languages_url": "https://api.github.com/repos/plove13x/hello-world/languages",
//         "stargazers_url": "https://api.github.com/repos/plove13x/hello-world/stargazers",
//         "contributors_url": "https://api.github.com/repos/plove13x/hello-world/contributors",
//         "subscribers_url": "https://api.github.com/repos/plove13x/hello-world/subscribers",
//         "subscription_url": "https://api.github.com/repos/plove13x/hello-world/subscription",
//         "commits_url": "https://api.github.com/repos/plove13x/hello-world/commits{/sha}",
//         "git_commits_url": "https://api.github.com/repos/plove13x/hello-world/git/commits{/sha}",
//         "comments_url": "https://api.github.com/repos/plove13x/hello-world/comments{/number}",
//         "issue_comment_url": "https://api.github.com/repos/plove13x/hello-world/issues/comments/{number}",
//         "contents_url": "https://api.github.com/repos/plove13x/hello-world/contents/{+path}",
//         "compare_url": "https://api.github.com/repos/plove13x/hello-world/compare/{base}...{head}",
//         "merges_url": "https://api.github.com/repos/plove13x/hello-world/merges",
//         "archive_url": "https://api.github.com/repos/plove13x/hello-world/{archive_format}{/ref}",
//         "downloads_url": "https://api.github.com/repos/plove13x/hello-world/downloads",
//         "issues_url": "https://api.github.com/repos/plove13x/hello-world/issues{/number}",
//         "pulls_url": "https://api.github.com/repos/plove13x/hello-world/pulls{/number}",
//         "milestones_url": "https://api.github.com/repos/plove13x/hello-world/milestones{/number}",
//         "notifications_url": "https://api.github.com/repos/plove13x/hello-world/notifications{?since,all,participating}",
//         "labels_url": "https://api.github.com/repos/plove13x/hello-world/labels{/name}",
//         "releases_url": "https://api.github.com/repos/plove13x/hello-world/releases{/id}",
//         "created_at": "2014-08-19T21:50:46Z",
//         "updated_at": "2014-08-19T21:50:46Z",
//         "pushed_at": "2014-08-19T22:06:42Z",
//         "git_url": "git://github.com/plove13x/hello-world.git",
//         "ssh_url": "git@github.com:plove13x/hello-world.git",
//         "clone_url": "https://github.com/plove13x/hello-world.git",
//         "svn_url": "https://github.com/plove13x/hello-world",
//         "homepage": null,
//         "size": 148,
//         "stargazers_count": 0,
//         "watchers_count": 0,
//         "language": null,
//         "has_issues": true,
//         "has_downloads": true,
//         "has_wiki": true,
//         "forks_count": 0,
//         "mirror_url": null,
//         "open_issues_count": 0,
//         "forks": 0,
//         "open_issues": 0,
//         "watchers": 0,
//         "default_branch": "master"
//     },
//     {
//         "id": 23634093,
//         "name": "JSChooseGoose",
//         "full_name": "plove13x/JSChooseGoose",
//         "owner": {
//             "login": "plove13x",
//             "id": 7731175,
//             "avatar_url": "https://avatars.githubusercontent.com/u/7731175?v=2",
//             "gravatar_id": "f6bfe421126c91d30029e954e8f1ee26",
//             "url": "https://api.github.com/users/plove13x",
//             "html_url": "https://github.com/plove13x",
//             "followers_url": "https://api.github.com/users/plove13x/followers",
//             "following_url": "https://api.github.com/users/plove13x/following{/other_user}",
//             "gists_url": "https://api.github.com/users/plove13x/gists{/gist_id}",
//             "starred_url": "https://api.github.com/users/plove13x/starred{/owner}{/repo}",
//             "subscriptions_url": "https://api.github.com/users/plove13x/subscriptions",
//             "organizations_url": "https://api.github.com/users/plove13x/orgs",
//             "repos_url": "https://api.github.com/users/plove13x/repos",
//             "events_url": "https://api.github.com/users/plove13x/events{/privacy}",
//             "received_events_url": "https://api.github.com/users/plove13x/received_events",
//             "type": "User",
//             "site_admin": false
//         },
//         "private": false,
//         "html_url": "https://github.com/plove13x/JSChooseGoose",
//         "description": null,
//         "fork": false,
//         "url": "https://api.github.com/repos/plove13x/JSChooseGoose",
//         "forks_url": "https://api.github.com/repos/plove13x/JSChooseGoose/forks",
//         "keys_url": "https://api.github.com/repos/plove13x/JSChooseGoose/keys{/key_id}",
//         "collaborators_url": "https://api.github.com/repos/plove13x/JSChooseGoose/collaborators{/collaborator}",
//         "teams_url": "https://api.github.com/repos/plove13x/JSChooseGoose/teams",
//         "hooks_url": "https://api.github.com/repos/plove13x/JSChooseGoose/hooks",
//         "issue_events_url": "https://api.github.com/repos/plove13x/JSChooseGoose/issues/events{/number}",
//         "events_url": "https://api.github.com/repos/plove13x/JSChooseGoose/events",
//         "assignees_url": "https://api.github.com/repos/plove13x/JSChooseGoose/assignees{/user}",
//         "branches_url": "https://api.github.com/repos/plove13x/JSChooseGoose/branches{/branch}",
//         "tags_url": "https://api.github.com/repos/plove13x/JSChooseGoose/tags",
//         "blobs_url": "https://api.github.com/repos/plove13x/JSChooseGoose/git/blobs{/sha}",
//         "git_tags_url": "https://api.github.com/repos/plove13x/JSChooseGoose/git/tags{/sha}",
//         "git_refs_url": "https://api.github.com/repos/plove13x/JSChooseGoose/git/refs{/sha}",
//         "trees_url": "https://api.github.com/repos/plove13x/JSChooseGoose/git/trees{/sha}",
//         "statuses_url": "https://api.github.com/repos/plove13x/JSChooseGoose/statuses/{sha}",
//         "languages_url": "https://api.github.com/repos/plove13x/JSChooseGoose/languages",
//         "stargazers_url": "https://api.github.com/repos/plove13x/JSChooseGoose/stargazers",
//         "contributors_url": "https://api.github.com/repos/plove13x/JSChooseGoose/contributors",
//         "subscribers_url": "https://api.github.com/repos/plove13x/JSChooseGoose/subscribers",
//         "subscription_url": "https://api.github.com/repos/plove13x/JSChooseGoose/subscription",
//         "commits_url": "https://api.github.com/repos/plove13x/JSChooseGoose/commits{/sha}",
//         "git_commits_url": "https://api.github.com/repos/plove13x/JSChooseGoose/git/commits{/sha}",
//         "comments_url": "https://api.github.com/repos/plove13x/JSChooseGoose/comments{/number}",
//         "issue_comment_url": "https://api.github.com/repos/plove13x/JSChooseGoose/issues/comments/{number}",
//         "contents_url": "https://api.github.com/repos/plove13x/JSChooseGoose/contents/{+path}",
//         "compare_url": "https://api.github.com/repos/plove13x/JSChooseGoose/compare/{base}...{head}",
//         "merges_url": "https://api.github.com/repos/plove13x/JSChooseGoose/merges",
//         "archive_url": "https://api.github.com/repos/plove13x/JSChooseGoose/{archive_format}{/ref}",
//         "downloads_url": "https://api.github.com/repos/plove13x/JSChooseGoose/downloads",
//         "issues_url": "https://api.github.com/repos/plove13x/JSChooseGoose/issues{/number}",
//         "pulls_url": "https://api.github.com/repos/plove13x/JSChooseGoose/pulls{/number}",
//         "milestones_url": "https://api.github.com/repos/plove13x/JSChooseGoose/milestones{/number}",
//         "notifications_url": "https://api.github.com/repos/plove13x/JSChooseGoose/notifications{?since,all,participating}",
//         "labels_url": "https://api.github.com/repos/plove13x/JSChooseGoose/labels{/name}",
//         "releases_url": "https://api.github.com/repos/plove13x/JSChooseGoose/releases{/id}",
//         "created_at": "2014-09-03T19:22:51Z",
//         "updated_at": "2014-09-03T19:23:10Z",
//         "pushed_at": "2014-09-03T19:23:10Z",
//         "git_url": "git://github.com/plove13x/JSChooseGoose.git",
//         "ssh_url": "git@github.com:plove13x/JSChooseGoose.git",
//         "clone_url": "https://github.com/plove13x/JSChooseGoose.git",
//         "svn_url": "https://github.com/plove13x/JSChooseGoose",
//         "homepage": null,
//         "size": 100,
//         "stargazers_count": 0,
//         "watchers_count": 0,
//         "language": "JavaScript",
//         "has_issues": true,
//         "has_downloads": true,
//         "has_wiki": true,
//         "forks_count": 0,
//         "mirror_url": null,
//         "open_issues_count": 0,
//         "forks": 0,
//         "open_issues": 0,
//         "watchers": 0,
//         "default_branch": "master"
//     },
//     {
//         "id": 23410560,
//         "name": "Lists",
//         "full_name": "plove13x/Lists",
//         "owner": {
//             "login": "plove13x",
//             "id": 7731175,
//             "avatar_url": "https://avatars.githubusercontent.com/u/7731175?v=2",
//             "gravatar_id": "f6bfe421126c91d30029e954e8f1ee26",
//             "url": "https://api.github.com/users/plove13x",
//             "html_url": "https://github.com/plove13x",
//             "followers_url": "https://api.github.com/users/plove13x/followers",
//             "following_url": "https://api.github.com/users/plove13x/following{/other_user}",
//             "gists_url": "https://api.github.com/users/plove13x/gists{/gist_id}",
//             "starred_url": "https://api.github.com/users/plove13x/starred{/owner}{/repo}",
//             "subscriptions_url": "https://api.github.com/users/plove13x/subscriptions",
//             "organizations_url": "https://api.github.com/users/plove13x/orgs",
//             "repos_url": "https://api.github.com/users/plove13x/repos",
//             "events_url": "https://api.github.com/users/plove13x/events{/privacy}",
//             "received_events_url": "https://api.github.com/users/plove13x/received_events",
//             "type": "User",
//             "site_admin": false
//         },
//         "private": false,
//         "html_url": "https://github.com/plove13x/Lists",
//         "description": null,
//         "fork": false,
//         "url": "https://api.github.com/repos/plove13x/Lists",
//         "forks_url": "https://api.github.com/repos/plove13x/Lists/forks",
//         "keys_url": "https://api.github.com/repos/plove13x/Lists/keys{/key_id}",
//         "collaborators_url": "https://api.github.com/repos/plove13x/Lists/collaborators{/collaborator}",
//         "teams_url": "https://api.github.com/repos/plove13x/Lists/teams",
//         "hooks_url": "https://api.github.com/repos/plove13x/Lists/hooks",
//         "issue_events_url": "https://api.github.com/repos/plove13x/Lists/issues/events{/number}",
//         "events_url": "https://api.github.com/repos/plove13x/Lists/events",
//         "assignees_url": "https://api.github.com/repos/plove13x/Lists/assignees{/user}",
//         "branches_url": "https://api.github.com/repos/plove13x/Lists/branches{/branch}",
//         "tags_url": "https://api.github.com/repos/plove13x/Lists/tags",
//         "blobs_url": "https://api.github.com/repos/plove13x/Lists/git/blobs{/sha}",
//         "git_tags_url": "https://api.github.com/repos/plove13x/Lists/git/tags{/sha}",
//         "git_refs_url": "https://api.github.com/repos/plove13x/Lists/git/refs{/sha}",
//         "trees_url": "https://api.github.com/repos/plove13x/Lists/git/trees{/sha}",
//         "statuses_url": "https://api.github.com/repos/plove13x/Lists/statuses/{sha}",
//         "languages_url": "https://api.github.com/repos/plove13x/Lists/languages",
//         "stargazers_url": "https://api.github.com/repos/plove13x/Lists/stargazers",
//         "contributors_url": "https://api.github.com/repos/plove13x/Lists/contributors",
//         "subscribers_url": "https://api.github.com/repos/plove13x/Lists/subscribers",
//         "subscription_url": "https://api.github.com/repos/plove13x/Lists/subscription",
//         "commits_url": "https://api.github.com/repos/plove13x/Lists/commits{/sha}",
//         "git_commits_url": "https://api.github.com/repos/plove13x/Lists/git/commits{/sha}",
//         "comments_url": "https://api.github.com/repos/plove13x/Lists/comments{/number}",
//         "issue_comment_url": "https://api.github.com/repos/plove13x/Lists/issues/comments/{number}",
//         "contents_url": "https://api.github.com/repos/plove13x/Lists/contents/{+path}",
//         "compare_url": "https://api.github.com/repos/plove13x/Lists/compare/{base}...{head}",
//         "merges_url": "https://api.github.com/repos/plove13x/Lists/merges",
//         "archive_url": "https://api.github.com/repos/plove13x/Lists/{archive_format}{/ref}",
//         "downloads_url": "https://api.github.com/repos/plove13x/Lists/downloads",
//         "issues_url": "https://api.github.com/repos/plove13x/Lists/issues{/number}",
//         "pulls_url": "https://api.github.com/repos/plove13x/Lists/pulls{/number}",
//         "milestones_url": "https://api.github.com/repos/plove13x/Lists/milestones{/number}",
//         "notifications_url": "https://api.github.com/repos/plove13x/Lists/notifications{?since,all,participating}",
//         "labels_url": "https://api.github.com/repos/plove13x/Lists/labels{/name}",
//         "releases_url": "https://api.github.com/repos/plove13x/Lists/releases{/id}",
//         "created_at": "2014-08-28T01:00:36Z",
//         "updated_at": "2014-08-28T01:00:55Z",
//         "pushed_at": "2014-08-28T01:00:54Z",
//         "git_url": "git://github.com/plove13x/Lists.git",
//         "ssh_url": "git@github.com:plove13x/Lists.git",
//         "clone_url": "https://github.com/plove13x/Lists.git",
//         "svn_url": "https://github.com/plove13x/Lists",
//         "homepage": null,
//         "size": 104,
//         "stargazers_count": 0,
//         "watchers_count": 0,
//         "language": "CSS",
//         "has_issues": true,
//         "has_downloads": true,
//         "has_wiki": true,
//         "forks_count": 0,
//         "mirror_url": null,
//         "open_issues_count": 0,
//         "forks": 0,
//         "open_issues": 0,
//         "watchers": 0,
//         "default_branch": "master"
//     },
//     {
//         "id": 23620710,
//         "name": "Notes",
//         "full_name": "plove13x/Notes",
//         "owner": {
//             "login": "plove13x",
//             "id": 7731175,
//             "avatar_url": "https://avatars.githubusercontent.com/u/7731175?v=2",
//             "gravatar_id": "f6bfe421126c91d30029e954e8f1ee26",
//             "url": "https://api.github.com/users/plove13x",
//             "html_url": "https://github.com/plove13x",
//             "followers_url": "https://api.github.com/users/plove13x/followers",
//             "following_url": "https://api.github.com/users/plove13x/following{/other_user}",
//             "gists_url": "https://api.github.com/users/plove13x/gists{/gist_id}",
//             "starred_url": "https://api.github.com/users/plove13x/starred{/owner}{/repo}",
//             "subscriptions_url": "https://api.github.com/users/plove13x/subscriptions",
//             "organizations_url": "https://api.github.com/users/plove13x/orgs",
//             "repos_url": "https://api.github.com/users/plove13x/repos",
//             "events_url": "https://api.github.com/users/plove13x/events{/privacy}",
//             "received_events_url": "https://api.github.com/users/plove13x/received_events",
//             "type": "User",
//             "site_admin": false
//         },
//         "private": false,
//         "html_url": "https://github.com/plove13x/Notes",
//         "description": null,
//         "fork": true,
//         "url": "https://api.github.com/repos/plove13x/Notes",
//         "forks_url": "https://api.github.com/repos/plove13x/Notes/forks",
//         "keys_url": "https://api.github.com/repos/plove13x/Notes/keys{/key_id}",
//         "collaborators_url": "https://api.github.com/repos/plove13x/Notes/collaborators{/collaborator}",
//         "teams_url": "https://api.github.com/repos/plove13x/Notes/teams",
//         "hooks_url": "https://api.github.com/repos/plove13x/Notes/hooks",
//         "issue_events_url": "https://api.github.com/repos/plove13x/Notes/issues/events{/number}",
//         "events_url": "https://api.github.com/repos/plove13x/Notes/events",
//         "assignees_url": "https://api.github.com/repos/plove13x/Notes/assignees{/user}",
//         "branches_url": "https://api.github.com/repos/plove13x/Notes/branches{/branch}",
//         "tags_url": "https://api.github.com/repos/plove13x/Notes/tags",
//         "blobs_url": "https://api.github.com/repos/plove13x/Notes/git/blobs{/sha}",
//         "git_tags_url": "https://api.github.com/repos/plove13x/Notes/git/tags{/sha}",
//         "git_refs_url": "https://api.github.com/repos/plove13x/Notes/git/refs{/sha}",
//         "trees_url": "https://api.github.com/repos/plove13x/Notes/git/trees{/sha}",
//         "statuses_url": "https://api.github.com/repos/plove13x/Notes/statuses/{sha}",
//         "languages_url": "https://api.github.com/repos/plove13x/Notes/languages",
//         "stargazers_url": "https://api.github.com/repos/plove13x/Notes/stargazers",
//         "contributors_url": "https://api.github.com/repos/plove13x/Notes/contributors",
//         "subscribers_url": "https://api.github.com/repos/plove13x/Notes/subscribers",
//         "subscription_url": "https://api.github.com/repos/plove13x/Notes/subscription",
//         "commits_url": "https://api.github.com/repos/plove13x/Notes/commits{/sha}",
//         "git_commits_url": "https://api.github.com/repos/plove13x/Notes/git/commits{/sha}",
//         "comments_url": "https://api.github.com/repos/plove13x/Notes/comments{/number}",
//         "issue_comment_url": "https://api.github.com/repos/plove13x/Notes/issues/comments/{number}",
//         "contents_url": "https://api.github.com/repos/plove13x/Notes/contents/{+path}",
//         "compare_url": "https://api.github.com/repos/plove13x/Notes/compare/{base}...{head}",
//         "merges_url": "https://api.github.com/repos/plove13x/Notes/merges",
//         "archive_url": "https://api.github.com/repos/plove13x/Notes/{archive_format}{/ref}",
//         "downloads_url": "https://api.github.com/repos/plove13x/Notes/downloads",
//         "issues_url": "https://api.github.com/repos/plove13x/Notes/issues{/number}",
//         "pulls_url": "https://api.github.com/repos/plove13x/Notes/pulls{/number}",
//         "milestones_url": "https://api.github.com/repos/plove13x/Notes/milestones{/number}",
//         "notifications_url": "https://api.github.com/repos/plove13x/Notes/notifications{?since,all,participating}",
//         "labels_url": "https://api.github.com/repos/plove13x/Notes/labels{/name}",
//         "releases_url": "https://api.github.com/repos/plove13x/Notes/releases{/id}",
//         "created_at": "2014-09-03T13:12:51Z",
//         "updated_at": "2014-09-02T13:17:19Z",
//         "pushed_at": "2014-09-02T16:47:11Z",
//         "git_url": "git://github.com/plove13x/Notes.git",
//         "ssh_url": "git@github.com:plove13x/Notes.git",
//         "clone_url": "https://github.com/plove13x/Notes.git",
//         "svn_url": "https://github.com/plove13x/Notes",
//         "homepage": null,
//         "size": 60,
//         "stargazers_count": 0,
//         "watchers_count": 0,
//         "language": null,
//         "has_issues": false,
//         "has_downloads": true,
//         "has_wiki": true,
//         "forks_count": 0,
//         "mirror_url": null,
//         "open_issues_count": 0,
//         "forks": 0,
//         "open_issues": 0,
//         "watchers": 0,
//         "default_branch": "master"
//     },
//     {
//         "id": 23394690,
//         "name": "Octodex",
//         "full_name": "plove13x/Octodex",
//         "owner": {
//             "login": "plove13x",
//             "id": 7731175,
//             "avatar_url": "https://avatars.githubusercontent.com/u/7731175?v=2",
//             "gravatar_id": "f6bfe421126c91d30029e954e8f1ee26",
//             "url": "https://api.github.com/users/plove13x",
//             "html_url": "https://github.com/plove13x",
//             "followers_url": "https://api.github.com/users/plove13x/followers",
//             "following_url": "https://api.github.com/users/plove13x/following{/other_user}",
//             "gists_url": "https://api.github.com/users/plove13x/gists{/gist_id}",
//             "starred_url": "https://api.github.com/users/plove13x/starred{/owner}{/repo}",
//             "subscriptions_url": "https://api.github.com/users/plove13x/subscriptions",
//             "organizations_url": "https://api.github.com/users/plove13x/orgs",
//             "repos_url": "https://api.github.com/users/plove13x/repos",
//             "events_url": "https://api.github.com/users/plove13x/events{/privacy}",
//             "received_events_url": "https://api.github.com/users/plove13x/received_events",
//             "type": "User",
//             "site_admin": false
//         },
//         "private": false,
//         "html_url": "https://github.com/plove13x/Octodex",
//         "description": null,
//         "fork": false,
//         "url": "https://api.github.com/repos/plove13x/Octodex",
//         "forks_url": "https://api.github.com/repos/plove13x/Octodex/forks",
//         "keys_url": "https://api.github.com/repos/plove13x/Octodex/keys{/key_id}",
//         "collaborators_url": "https://api.github.com/repos/plove13x/Octodex/collaborators{/collaborator}",
//         "teams_url": "https://api.github.com/repos/plove13x/Octodex/teams",
//         "hooks_url": "https://api.github.com/repos/plove13x/Octodex/hooks",
//         "issue_events_url": "https://api.github.com/repos/plove13x/Octodex/issues/events{/number}",
//         "events_url": "https://api.github.com/repos/plove13x/Octodex/events",
//         "assignees_url": "https://api.github.com/repos/plove13x/Octodex/assignees{/user}",
//         "branches_url": "https://api.github.com/repos/plove13x/Octodex/branches{/branch}",
//         "tags_url": "https://api.github.com/repos/plove13x/Octodex/tags",
//         "blobs_url": "https://api.github.com/repos/plove13x/Octodex/git/blobs{/sha}",
//         "git_tags_url": "https://api.github.com/repos/plove13x/Octodex/git/tags{/sha}",
//         "git_refs_url": "https://api.github.com/repos/plove13x/Octodex/git/refs{/sha}",
//         "trees_url": "https://api.github.com/repos/plove13x/Octodex/git/trees{/sha}",
//         "statuses_url": "https://api.github.com/repos/plove13x/Octodex/statuses/{sha}",
//         "languages_url": "https://api.github.com/repos/plove13x/Octodex/languages",
//         "stargazers_url": "https://api.github.com/repos/plove13x/Octodex/stargazers",
//         "contributors_url": "https://api.github.com/repos/plove13x/Octodex/contributors",
//         "subscribers_url": "https://api.github.com/repos/plove13x/Octodex/subscribers",
//         "subscription_url": "https://api.github.com/repos/plove13x/Octodex/subscription",
//         "commits_url": "https://api.github.com/repos/plove13x/Octodex/commits{/sha}",
//         "git_commits_url": "https://api.github.com/repos/plove13x/Octodex/git/commits{/sha}",
//         "comments_url": "https://api.github.com/repos/plove13x/Octodex/comments{/number}",
//         "issue_comment_url": "https://api.github.com/repos/plove13x/Octodex/issues/comments/{number}",
//         "contents_url": "https://api.github.com/repos/plove13x/Octodex/contents/{+path}",
//         "compare_url": "https://api.github.com/repos/plove13x/Octodex/compare/{base}...{head}",
//         "merges_url": "https://api.github.com/repos/plove13x/Octodex/merges",
//         "archive_url": "https://api.github.com/repos/plove13x/Octodex/{archive_format}{/ref}",
//         "downloads_url": "https://api.github.com/repos/plove13x/Octodex/downloads",
//         "issues_url": "https://api.github.com/repos/plove13x/Octodex/issues{/number}",
//         "pulls_url": "https://api.github.com/repos/plove13x/Octodex/pulls{/number}",
//         "milestones_url": "https://api.github.com/repos/plove13x/Octodex/milestones{/number}",
//         "notifications_url": "https://api.github.com/repos/plove13x/Octodex/notifications{?since,all,participating}",
//         "labels_url": "https://api.github.com/repos/plove13x/Octodex/labels{/name}",
//         "releases_url": "https://api.github.com/repos/plove13x/Octodex/releases{/id}",
//         "created_at": "2014-08-27T15:22:32Z",
//         "updated_at": "2014-08-27T15:25:03Z",
//         "pushed_at": "2014-08-27T15:25:04Z",
//         "git_url": "git://github.com/plove13x/Octodex.git",
//         "ssh_url": "git@github.com:plove13x/Octodex.git",
//         "clone_url": "https://github.com/plove13x/Octodex.git",
//         "svn_url": "https://github.com/plove13x/Octodex",
//         "homepage": null,
//         "size": 104,
//         "stargazers_count": 0,
//         "watchers_count": 0,
//         "language": "CSS",
//         "has_issues": true,
//         "has_downloads": true,
//         "has_wiki": true,
//         "forks_count": 0,
//         "mirror_url": null,
//         "open_issues_count": 0,
//         "forks": 0,
//         "open_issues": 0,
//         "watchers": 0,
//         "default_branch": "master"
//     },
//     {
//         "id": 23568130,
//         "name": "Surf",
//         "full_name": "plove13x/Surf",
//         "owner": {
//             "login": "plove13x",
//             "id": 7731175,
//             "avatar_url": "https://avatars.githubusercontent.com/u/7731175?v=2",
//             "gravatar_id": "f6bfe421126c91d30029e954e8f1ee26",
//             "url": "https://api.github.com/users/plove13x",
//             "html_url": "https://github.com/plove13x",
//             "followers_url": "https://api.github.com/users/plove13x/followers",
//             "following_url": "https://api.github.com/users/plove13x/following{/other_user}",
//             "gists_url": "https://api.github.com/users/plove13x/gists{/gist_id}",
//             "starred_url": "https://api.github.com/users/plove13x/starred{/owner}{/repo}",
//             "subscriptions_url": "https://api.github.com/users/plove13x/subscriptions",
//             "organizations_url": "https://api.github.com/users/plove13x/orgs",
//             "repos_url": "https://api.github.com/users/plove13x/repos",
//             "events_url": "https://api.github.com/users/plove13x/events{/privacy}",
//             "received_events_url": "https://api.github.com/users/plove13x/received_events",
//             "type": "User",
//             "site_admin": false
//         },
//         "private": false,
//         "html_url": "https://github.com/plove13x/Surf",
//         "description": null,
//         "fork": false,
//         "url": "https://api.github.com/repos/plove13x/Surf",
//         "forks_url": "https://api.github.com/repos/plove13x/Surf/forks",
//         "keys_url": "https://api.github.com/repos/plove13x/Surf/keys{/key_id}",
//         "collaborators_url": "https://api.github.com/repos/plove13x/Surf/collaborators{/collaborator}",
//         "teams_url": "https://api.github.com/repos/plove13x/Surf/teams",
//         "hooks_url": "https://api.github.com/repos/plove13x/Surf/hooks",
//         "issue_events_url": "https://api.github.com/repos/plove13x/Surf/issues/events{/number}",
//         "events_url": "https://api.github.com/repos/plove13x/Surf/events",
//         "assignees_url": "https://api.github.com/repos/plove13x/Surf/assignees{/user}",
//         "branches_url": "https://api.github.com/repos/plove13x/Surf/branches{/branch}",
//         "tags_url": "https://api.github.com/repos/plove13x/Surf/tags",
//         "blobs_url": "https://api.github.com/repos/plove13x/Surf/git/blobs{/sha}",
//         "git_tags_url": "https://api.github.com/repos/plove13x/Surf/git/tags{/sha}",
//         "git_refs_url": "https://api.github.com/repos/plove13x/Surf/git/refs{/sha}",
//         "trees_url": "https://api.github.com/repos/plove13x/Surf/git/trees{/sha}",
//         "statuses_url": "https://api.github.com/repos/plove13x/Surf/statuses/{sha}",
//         "languages_url": "https://api.github.com/repos/plove13x/Surf/languages",
//         "stargazers_url": "https://api.github.com/repos/plove13x/Surf/stargazers",
//         "contributors_url": "https://api.github.com/repos/plove13x/Surf/contributors",
//         "subscribers_url": "https://api.github.com/repos/plove13x/Surf/subscribers",
//         "subscription_url": "https://api.github.com/repos/plove13x/Surf/subscription",
//         "commits_url": "https://api.github.com/repos/plove13x/Surf/commits{/sha}",
//         "git_commits_url": "https://api.github.com/repos/plove13x/Surf/git/commits{/sha}",
//         "comments_url": "https://api.github.com/repos/plove13x/Surf/comments{/number}",
//         "issue_comment_url": "https://api.github.com/repos/plove13x/Surf/issues/comments/{number}",
//         "contents_url": "https://api.github.com/repos/plove13x/Surf/contents/{+path}",
//         "compare_url": "https://api.github.com/repos/plove13x/Surf/compare/{base}...{head}",
//         "merges_url": "https://api.github.com/repos/plove13x/Surf/merges",
//         "archive_url": "https://api.github.com/repos/plove13x/Surf/{archive_format}{/ref}",
//         "downloads_url": "https://api.github.com/repos/plove13x/Surf/downloads",
//         "issues_url": "https://api.github.com/repos/plove13x/Surf/issues{/number}",
//         "pulls_url": "https://api.github.com/repos/plove13x/Surf/pulls{/number}",
//         "milestones_url": "https://api.github.com/repos/plove13x/Surf/milestones{/number}",
//         "notifications_url": "https://api.github.com/repos/plove13x/Surf/notifications{?since,all,participating}",
//         "labels_url": "https://api.github.com/repos/plove13x/Surf/labels{/name}",
//         "releases_url": "https://api.github.com/repos/plove13x/Surf/releases{/id}",
//         "created_at": "2014-09-02T06:46:45Z",
//         "updated_at": "2014-09-02T06:48:58Z",
//         "pushed_at": "2014-09-02T06:48:57Z",
//         "git_url": "git://github.com/plove13x/Surf.git",
//         "ssh_url": "git@github.com:plove13x/Surf.git",
//         "clone_url": "https://github.com/plove13x/Surf.git",
//         "svn_url": "https://github.com/plove13x/Surf",
//         "homepage": null,
//         "size": 3192,
//         "stargazers_count": 0,
//         "watchers_count": 0,
//         "language": "CSS",
//         "has_issues": true,
//         "has_downloads": true,
//         "has_wiki": true,
//         "forks_count": 0,
//         "mirror_url": null,
//         "open_issues_count": 0,
//         "forks": 0,
//         "open_issues": 0,
//         "watchers": 0,
//         "default_branch": "master"
//     },
//     {
//         "id": 23608102,
//         "name": "SurfAndPaddleA5",
//         "full_name": "plove13x/SurfAndPaddleA5",
//         "owner": {
//             "login": "plove13x",
//             "id": 7731175,
//             "avatar_url": "https://avatars.githubusercontent.com/u/7731175?v=2",
//             "gravatar_id": "f6bfe421126c91d30029e954e8f1ee26",
//             "url": "https://api.github.com/users/plove13x",
//             "html_url": "https://github.com/plove13x",
//             "followers_url": "https://api.github.com/users/plove13x/followers",
//             "following_url": "https://api.github.com/users/plove13x/following{/other_user}",
//             "gists_url": "https://api.github.com/users/plove13x/gists{/gist_id}",
//             "starred_url": "https://api.github.com/users/plove13x/starred{/owner}{/repo}",
//             "subscriptions_url": "https://api.github.com/users/plove13x/subscriptions",
//             "organizations_url": "https://api.github.com/users/plove13x/orgs",
//             "repos_url": "https://api.github.com/users/plove13x/repos",
//             "events_url": "https://api.github.com/users/plove13x/events{/privacy}",
//             "received_events_url": "https://api.github.com/users/plove13x/received_events",
//             "type": "User",
//             "site_admin": false
//         },
//         "private": false,
//         "html_url": "https://github.com/plove13x/SurfAndPaddleA5",
//         "description": null,
//         "fork": false,
//         "url": "https://api.github.com/repos/plove13x/SurfAndPaddleA5",
//         "forks_url": "https://api.github.com/repos/plove13x/SurfAndPaddleA5/forks",
//         "keys_url": "https://api.github.com/repos/plove13x/SurfAndPaddleA5/keys{/key_id}",
//         "collaborators_url": "https://api.github.com/repos/plove13x/SurfAndPaddleA5/collaborators{/collaborator}",
//         "teams_url": "https://api.github.com/repos/plove13x/SurfAndPaddleA5/teams",
//         "hooks_url": "https://api.github.com/repos/plove13x/SurfAndPaddleA5/hooks",
//         "issue_events_url": "https://api.github.com/repos/plove13x/SurfAndPaddleA5/issues/events{/number}",
//         "events_url": "https://api.github.com/repos/plove13x/SurfAndPaddleA5/events",
//         "assignees_url": "https://api.github.com/repos/plove13x/SurfAndPaddleA5/assignees{/user}",
//         "branches_url": "https://api.github.com/repos/plove13x/SurfAndPaddleA5/branches{/branch}",
//         "tags_url": "https://api.github.com/repos/plove13x/SurfAndPaddleA5/tags",
//         "blobs_url": "https://api.github.com/repos/plove13x/SurfAndPaddleA5/git/blobs{/sha}",
//         "git_tags_url": "https://api.github.com/repos/plove13x/SurfAndPaddleA5/git/tags{/sha}",
//         "git_refs_url": "https://api.github.com/repos/plove13x/SurfAndPaddleA5/git/refs{/sha}",
//         "trees_url": "https://api.github.com/repos/plove13x/SurfAndPaddleA5/git/trees{/sha}",
//         "statuses_url": "https://api.github.com/repos/plove13x/SurfAndPaddleA5/statuses/{sha}",
//         "languages_url": "https://api.github.com/repos/plove13x/SurfAndPaddleA5/languages",
//         "stargazers_url": "https://api.github.com/repos/plove13x/SurfAndPaddleA5/stargazers",
//         "contributors_url": "https://api.github.com/repos/plove13x/SurfAndPaddleA5/contributors",
//         "subscribers_url": "https://api.github.com/repos/plove13x/SurfAndPaddleA5/subscribers",
//         "subscription_url": "https://api.github.com/repos/plove13x/SurfAndPaddleA5/subscription",
//         "commits_url": "https://api.github.com/repos/plove13x/SurfAndPaddleA5/commits{/sha}",
//         "git_commits_url": "https://api.github.com/repos/plove13x/SurfAndPaddleA5/git/commits{/sha}",
//         "comments_url": "https://api.github.com/repos/plove13x/SurfAndPaddleA5/comments{/number}",
//         "issue_comment_url": "https://api.github.com/repos/plove13x/SurfAndPaddleA5/issues/comments/{number}",
//         "contents_url": "https://api.github.com/repos/plove13x/SurfAndPaddleA5/contents/{+path}",
//         "compare_url": "https://api.github.com/repos/plove13x/SurfAndPaddleA5/compare/{base}...{head}",
//         "merges_url": "https://api.github.com/repos/plove13x/SurfAndPaddleA5/merges",
//         "archive_url": "https://api.github.com/repos/plove13x/SurfAndPaddleA5/{archive_format}{/ref}",
//         "downloads_url": "https://api.github.com/repos/plove13x/SurfAndPaddleA5/downloads",
//         "issues_url": "https://api.github.com/repos/plove13x/SurfAndPaddleA5/issues{/number}",
//         "pulls_url": "https://api.github.com/repos/plove13x/SurfAndPaddleA5/pulls{/number}",
//         "milestones_url": "https://api.github.com/repos/plove13x/SurfAndPaddleA5/milestones{/number}",
//         "notifications_url": "https://api.github.com/repos/plove13x/SurfAndPaddleA5/notifications{?since,all,participating}",
//         "labels_url": "https://api.github.com/repos/plove13x/SurfAndPaddleA5/labels{/name}",
//         "releases_url": "https://api.github.com/repos/plove13x/SurfAndPaddleA5/releases{/id}",
//         "created_at": "2014-09-03T05:47:41Z",
//         "updated_at": "2014-09-03T05:48:30Z",
//         "pushed_at": "2014-09-04T04:19:37Z",
//         "git_url": "git://github.com/plove13x/SurfAndPaddleA5.git",
//         "ssh_url": "git@github.com:plove13x/SurfAndPaddleA5.git",
//         "clone_url": "https://github.com/plove13x/SurfAndPaddleA5.git",
//         "svn_url": "https://github.com/plove13x/SurfAndPaddleA5",
//         "homepage": null,
//         "size": 7264,
//         "stargazers_count": 0,
//         "watchers_count": 0,
//         "language": "CSS",
//         "has_issues": true,
//         "has_downloads": true,
//         "has_wiki": true,
//         "forks_count": 0,
//         "mirror_url": null,
//         "open_issues_count": 0,
//         "forks": 0,
//         "open_issues": 0,
//         "watchers": 0,
//         "default_branch": "master"
//     },
//     {
//         "id": 20387162,
//         "name": "Yearn2Learn",
//         "full_name": "plove13x/Yearn2Learn",
//         "owner": {
//             "login": "plove13x",
//             "id": 7731175,
//             "avatar_url": "https://avatars.githubusercontent.com/u/7731175?v=2",
//             "gravatar_id": "f6bfe421126c91d30029e954e8f1ee26",
//             "url": "https://api.github.com/users/plove13x",
//             "html_url": "https://github.com/plove13x",
//             "followers_url": "https://api.github.com/users/plove13x/followers",
//             "following_url": "https://api.github.com/users/plove13x/following{/other_user}",
//             "gists_url": "https://api.github.com/users/plove13x/gists{/gist_id}",
//             "starred_url": "https://api.github.com/users/plove13x/starred{/owner}{/repo}",
//             "subscriptions_url": "https://api.github.com/users/plove13x/subscriptions",
//             "organizations_url": "https://api.github.com/users/plove13x/orgs",
//             "repos_url": "https://api.github.com/users/plove13x/repos",
//             "events_url": "https://api.github.com/users/plove13x/events{/privacy}",
//             "received_events_url": "https://api.github.com/users/plove13x/received_events",
//             "type": "User",
//             "site_admin": false
//         },
//         "private": false,
//         "html_url": "https://github.com/plove13x/Yearn2Learn",
//         "description": "Doubt there's anything innovative here. Just figured I might as well start logging what I've built+understood. ",
//         "fork": false,
//         "url": "https://api.github.com/repos/plove13x/Yearn2Learn",
//         "forks_url": "https://api.github.com/repos/plove13x/Yearn2Learn/forks",
//         "keys_url": "https://api.github.com/repos/plove13x/Yearn2Learn/keys{/key_id}",
//         "collaborators_url": "https://api.github.com/repos/plove13x/Yearn2Learn/collaborators{/collaborator}",
//         "teams_url": "https://api.github.com/repos/plove13x/Yearn2Learn/teams",
//         "hooks_url": "https://api.github.com/repos/plove13x/Yearn2Learn/hooks",
//         "issue_events_url": "https://api.github.com/repos/plove13x/Yearn2Learn/issues/events{/number}",
//         "events_url": "https://api.github.com/repos/plove13x/Yearn2Learn/events",
//         "assignees_url": "https://api.github.com/repos/plove13x/Yearn2Learn/assignees{/user}",
//         "branches_url": "https://api.github.com/repos/plove13x/Yearn2Learn/branches{/branch}",
//         "tags_url": "https://api.github.com/repos/plove13x/Yearn2Learn/tags",
//         "blobs_url": "https://api.github.com/repos/plove13x/Yearn2Learn/git/blobs{/sha}",
//         "git_tags_url": "https://api.github.com/repos/plove13x/Yearn2Learn/git/tags{/sha}",
//         "git_refs_url": "https://api.github.com/repos/plove13x/Yearn2Learn/git/refs{/sha}",
//         "trees_url": "https://api.github.com/repos/plove13x/Yearn2Learn/git/trees{/sha}",
//         "statuses_url": "https://api.github.com/repos/plove13x/Yearn2Learn/statuses/{sha}",
//         "languages_url": "https://api.github.com/repos/plove13x/Yearn2Learn/languages",
//         "stargazers_url": "https://api.github.com/repos/plove13x/Yearn2Learn/stargazers",
//         "contributors_url": "https://api.github.com/repos/plove13x/Yearn2Learn/contributors",
//         "subscribers_url": "https://api.github.com/repos/plove13x/Yearn2Learn/subscribers",
//         "subscription_url": "https://api.github.com/repos/plove13x/Yearn2Learn/subscription",
//         "commits_url": "https://api.github.com/repos/plove13x/Yearn2Learn/commits{/sha}",
//         "git_commits_url": "https://api.github.com/repos/plove13x/Yearn2Learn/git/commits{/sha}",
//         "comments_url": "https://api.github.com/repos/plove13x/Yearn2Learn/comments{/number}",
//         "issue_comment_url": "https://api.github.com/repos/plove13x/Yearn2Learn/issues/comments/{number}",
//         "contents_url": "https://api.github.com/repos/plove13x/Yearn2Learn/contents/{+path}",
//         "compare_url": "https://api.github.com/repos/plove13x/Yearn2Learn/compare/{base}...{head}",
//         "merges_url": "https://api.github.com/repos/plove13x/Yearn2Learn/merges",
//         "archive_url": "https://api.github.com/repos/plove13x/Yearn2Learn/{archive_format}{/ref}",
//         "downloads_url": "https://api.github.com/repos/plove13x/Yearn2Learn/downloads",
//         "issues_url": "https://api.github.com/repos/plove13x/Yearn2Learn/issues{/number}",
//         "pulls_url": "https://api.github.com/repos/plove13x/Yearn2Learn/pulls{/number}",
//         "milestones_url": "https://api.github.com/repos/plove13x/Yearn2Learn/milestones{/number}",
//         "notifications_url": "https://api.github.com/repos/plove13x/Yearn2Learn/notifications{?since,all,participating}",
//         "labels_url": "https://api.github.com/repos/plove13x/Yearn2Learn/labels{/name}",
//         "releases_url": "https://api.github.com/repos/plove13x/Yearn2Learn/releases{/id}",
//         "created_at": "2014-06-01T21:44:13Z",
//         "updated_at": "2014-06-05T05:38:03Z",
//         "pushed_at": "2014-06-05T05:38:02Z",
//         "git_url": "git://github.com/plove13x/Yearn2Learn.git",
//         "ssh_url": "git@github.com:plove13x/Yearn2Learn.git",
//         "clone_url": "https://github.com/plove13x/Yearn2Learn.git",
//         "svn_url": "https://github.com/plove13x/Yearn2Learn",
//         "homepage": null,
//         "size": 128,
//         "stargazers_count": 0,
//         "watchers_count": 0,
//         "language": null,
//         "has_issues": true,
//         "has_downloads": true,
//         "has_wiki": true,
//         "forks_count": 0,
//         "mirror_url": null,
//         "open_issues_count": 0,
//         "forks": 0,
//         "open_issues": 0,
//         "watchers": 0,
//         "default_branch": "master"
//     }
// ];

// var ploveRepos = data.map(function(item) {
//     var smallerObj = {};                                
//     smallerObj.name = item.name;
//     smallerObj.html_url = item.html_url;
//     smallerObj.fork = item.fork;                                /*NOT IDEAL*/
//     //smallerObj.comments_url = item.comments_url;              /*HOW WOULD I EXTRACT THIS AND IS THIS EVEN THE RIGHT PROPERTY?*/
//     smallerObj.updated_at = moment(item.updated_at).fromNow();
//     return smallerObj;
// });


/*
ploveRepos.forEach(function(inputHere) {             
    var $li = $('<li class="repo">');
    $('ul').append($li)
    $li.append('<a class="name" href="' + inputHere.html_url + '">' + inputHere.name + '</a>');
    $li.append('<div class="fork">' + inputHere.fork + '</div>');
    //$li.append('<div class="comment">' + inputHere.comment + '</div>');               
    $li.append('<div class="updated_at">' + inputHere.updated_at + '</div>');            
});
*/

function renderTemplate(templateId, container, finalArgument) {
    var templateString = $('#' + templateId).text();
    var templateFunction = _.template(templateString);
    var renderedTemplate = templateFunction(finalArgument);
    $(container).append(renderedTemplate);
};

$.getJSON("https://api.github.com/users/plove13x/repos").done(function(data) {
    var ploveRepos = data.map(function(item) {
        return {
            "name": item.name,
            "html_url": item.html_url,
            "fork": item.fork,                              /*defaults/extends?*/
            //"comments_url": item.comments_url,            HOW WOULD I EXTRACT THIS AND IS THIS EVEN THE RIGHT PROPERTY?
            "updated_at": moment(item.updated_at).fromNow()    
        };
        /*var smallerObj = {};                                
        smallerObj.name = item.name;
        smallerObj.html_url = item.html_url;
        smallerObj.fork = item.fork;                              
        smallerObj.comments_url = item.comments_url;              
        smallerObj.updated_at = moment(item.updated_at).fromNow();
        return smallerObj;*/
    });
    _.each(ploveRepos, function(repo) {
        renderTemplate('reposTemplateScript', '.repos', repo);            
    });
});
/*
    _.each(ploveRepos, function(model) {
    var templateString = $('#reposTemplateScript').text();
    var templateFunction = _.template(templateString);
    var renderedTemplate = templateFunction(model);
    $('.repos').append(renderedTemplate);
    });
*/



$.getJSON("https://api.github.com/users/plove13x").done(function(item) {
    var userInfo = {
            "avatar_url": item.avatar_url,
            "name": item.name,
            "login": item.login,
            "company": item.company,                /*May need to use ternary here once you add icons*/
            "location": item.location,
            /*<span class="octicon octicon-mail"></span>        underscore defaults or extend?*/
            "email": item.email,
            "blog": item.blog,   
            "created_at": item.created_at && moment(item.created_at).fromNow(),
            "followers": item.followers,
            //"starred_url": item.starred_url,
            "following": item.following
            //"organizations_url": item.organizations_url
    };
    renderTemplate('sidebarTemplateScript', '.sidebar', userInfo); 
});


